### ISSUE TITLE
Add `configuration.tx_bucket_size`

### ISSUE THREAD

**Issue by myrho** [graphsense/graphsense-ethereum-etl#2]
There is `tx_bucket_size` in the configuration table of utxo currencies (see [here](https://github.com/graphsense/graphsense-blocksci/blob/develop/scripts/schema.cql#L72)) but no equivalent for ethereum (see [here](https://github.com/graphsense/graphsense-ethereum-etl/blob/develop/scripts/schema.cql#L92))

**Comment by defconst** [comment]
ETH transaction table is partitioned by `tx_hash_prefix`, `tx_prefix_length` is stored in `configuration` table
