### ISSUE TITLE
Missing transaction

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-ethereum-etl#4]
The following transaction is not found: 0x4320f8acbbd305db21e1da98f8ad03a41f8ad0527aad3594cf75842e82f99115

Do we know why?

**Comment by defconst** [comment]
![eth_tx](https://user-images.githubusercontent.com/165452/171432350-d17acb39-24b0-41ef-a172-e996e8e8ad4c.png)

Search does not work with 0x prefix

**Comment by defconst** [comment]
![eth_tx_gs](https://user-images.githubusercontent.com/165452/171433274-564e9ed9-6e6b-4a04-8d62-dd6bd969e775.png)

**Comment by behas** [comment]
Ok, then this should be considered on the UI or REST level because we many users might enter tx_hashes starting with 0x. Easy solution: just strip it
